[INFO][0][<module>] Linux derecho2 5.14.21-150400.24.18-default #1 SMP PREEMPT_DYNAMIC Thu Aug 4 14:17:48 UTC 2022 (e9f7bfc) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2024-01-09 06:53:16.405865
[DEBUG][6][WorkConfront][Albedo/CERES][ctsm51fates_derecho_norman_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][4][WorkConfront][Albedo/CERES][ctsm51fates_derecho_2s_sp]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][7][WorkConfront][Albedo/CERES][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 157, in confront
    obs, mod, obs_timeint, mod_timeint = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 44, in stageData
    dn_obs = Variable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Variable.py", line 140, in __init__
    out = il.FromNetCDF4(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 724, in FromNetCDF4
    dset = Dataset(filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
FileNotFoundError: [Errno 2] No such file or directory: b'/glade/work/rfisher/ILAMB_data/DATA/rsds/CERESed4.2/rsds.nc'

[DEBUG][1][extractTimeSeries][RTM_ens36_case_0] Could not find [hfls,le,EFLX_LH_TOT] in the model results
[DEBUG][3][extractTimeSeries][RTM_ens36_case_0] Could not find [hfss,sh,FSH] in the model results
[DEBUG][3][WorkConfront][SensibleHeat/WECANN][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][1][WorkConfront][LatentHeat/WECANN][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[DEBUG][0][extractTimeSeries][RTM_ens36_case_0] Could not find [QVEGE] in the model results
[DEBUG][0][WorkConfront][Evapotranspiration/MODIS][RTM_ens36_case_0]
Traceback (most recent call last):
  File "/glade/u/home/rfisher/fates-global-cal/ilamb_scripts/./ilamb-run", line 385, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 431, in confront
    obs, mod = self.stageData(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 369, in stageData
    mod = m.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 413, in extractTimeSeries
    v = self.derivedVariable(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 499, in derivedVariable
    Vs[arg] = self.extractTimeSeries(
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ModelResult.py", line 437, in extractTimeSeries
    raise il.VarNotInModel()
ILAMB.ilamblib.VarNotInModel: VarNotInModel

[INFO][6][modelPlots][Runoff/Dai][ctsm51fates_derecho_2s_sp] Success
[INFO][3][modelPlots][LatentHeat/WECANN][ctsm51fates_derecho_2s_sp] Success
[INFO][5][modelPlots][SensibleHeat/WECANN][ctsm51fates_derecho_2s_sp] Success
[INFO][1][modelPlots][Evapotranspiration/MODIS][ctsm51fates_derecho_2s_sp] Success
[INFO][4][modelPlots][SensibleHeat/Fluxcom][ctsm51fates_derecho_2s_sp] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/GBAF][ctsm51fates_derecho_2s_sp] Success
[INFO][3][modelPlots][LatentHeat/WECANN][ctsm51fates_derecho_norman_sp] Success
[INFO][2][modelPlots][LatentHeat/Fluxcom][ctsm51fates_derecho_2s_sp] Success
[INFO][5][modelPlots][SensibleHeat/WECANN][ctsm51fates_derecho_norman_sp] Success
[INFO][6][modelPlots][Runoff/Dai][ctsm51fates_derecho_norman_sp] Success
[INFO][1][modelPlots][Evapotranspiration/MODIS][ctsm51fates_derecho_norman_sp] Success
[INFO][4][modelPlots][SensibleHeat/Fluxcom][ctsm51fates_derecho_norman_sp] Success
[INFO][2][modelPlots][LatentHeat/Fluxcom][ctsm51fates_derecho_norman_sp] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/GBAF][ctsm51fates_derecho_norman_sp] Success
[INFO][2][modelPlots][LatentHeat/Fluxcom][RTM_ens36_case_0] Success
[INFO][4][modelPlots][SensibleHeat/Fluxcom][RTM_ens36_case_0] Success
[INFO][0][modelPlots][GrossPrimaryProductivity/GBAF][RTM_ens36_case_0] Success
[INFO][6][modelPlots][Runoff/Dai][RTM_ens36_case_0] Success
[INFO][7][<module>][process time] 0.0 s
[INFO][1][<module>][process time] 13.6 s
[INFO][6][<module>][process time] 36.1 s
[INFO][4][<module>][process time] 21.6 s
[INFO][5][<module>][process time] 8.7 s
[INFO][2][<module>][process time] 20.8 s
[INFO][0][<module>][process time] 25.0 s
[INFO][3][<module>][process time] 10.9 s
[INFO][0][<module>][total time] 81.3 s
[INFO][0][<module>][process balance] 261700.18
[INFO][0][<module>][parallel efficiency] 21%
